# Generated by Django 3.1.2 on 2020-10-23 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='type',
            field=models.CharField(default='', max_length=30),
        ),
    ]
